### ISSUE TITLE
Motor model

### ISSUE THREAD

**Issue by fcaponetto** [popi-mkx3/popi_project#2]
Hi! 
First, I would say that your project is very interesting!

I am curious about the kind of motors you have been using in this project. Are you currently using BLDC motors?

Thanks in andance

**Comment by popi-mkx3** [comment]
Hi Fernando,



Thanks for your feedback!



No, our motors are not brushless but brushed.

But this is not the best solution. We prefer to present you our errors and
what we get out of them :



*What we have done ;*

- A fairly heavy and oversized structure (22.5kg without actuators) due to
the imposed raw materials (aluminum and steel), the time that we lacked to
simulate (oversizing), and our lack of experience.

- An underestimated weight constraint in the choice of actuators. The power
to weight ratio being very very important in this area.

- Over-sizing of the initial torque requirement.

- Underestimate the problem of EMI (electromagnetic interference), which is
stronger in brushed motors and which caused us a lot of noise problems at
the end of the project.

This led us to choose heavy brushed motors with a high torque (120Nm) which
essentially serves to compensate for the weight of the actuators themselves
(48kg of actuators).



*What should rather be done;*

*Take BLDCs* that have a better power-to-weight ratio and fewer EMI
problems. Ideally brushless like those used for drones, like T-motors for
example, which are very light.



We are currently designing the Popi V2, our actuators now weigh less than
500 grams compared to the average 4kg for those of the V1. Also, we are now
using much lighter materials for the structure (mostly 3D-printed). These
developments should allow us afterwards to have a new Popi of only 20kg
maximum.



Do not hesitate if you have any question, we will answer with pleasure.



Looking forward to reading you,

POPI Team
