### ISSUE TITLE
Popi's Equation of motion in every gaits of legs and base.

### ISSUE THREAD

**Issue by UchidaKouki** [popi-mkx3/popi_project#3]
Hello, everyone.
I have a new question about Popi.
I want to know about Popi's equation of motion in every gaits of legs and base.
I'm a collage student and studying about 4-legged robot simulation.  

Popi simulates motion and path of robot by using system of Towr. 
I found this repogitory during studying about Towr. 
ALEXANDER in ETH Zurich published paper about kinematics of 4-legged robot, Towr and Xpp 
He also introduced the paper in his repogitory.

Robot models of Popi is deferent from Xpp, so I searched paper which wrote about Popi, because I want to study Popi's kinematics anew. 
But I couldn't find the paper in the web.
I apologize my low level ability of searching paper.

If you published the paper which wrote about Popi's kinematics or equation of motion in formula, can you tell me where is the paper?
If possible, please tell me about Popi's kinematics or equation of motion in this issue?

**Comment by popi-mkx3** [comment]
Hello HuchidaKouki,

Sorry about that, we actually did not publish any paper about Popi's kinematics. The equations are located [here](https://github.com/popi-mkx3/popi_project/blob/master/popi_software/towr/xpp/robots/xpp_popi/src/popileg_inverse_kinematics.cc) , just in case you didn't find them.

I actually calculated those equations using the modified Denavit-Hartemberg method, but it was all handwriting, backed up by long-lost Matlab's files. I am currently lacking the time to put the whole work into a numerical format, but I just quickly rewrote the transformation matrix using the modified Denavit-Hartemberg convention, so that you can give it a try. You should easily come up to the solution.

[Transformation matrix.pdf](https://github.com/popi-mkx3/popi_project/files/5305177/Transformation.matrix.pdf)


Please let me know if this is enough to help you. Otherwise I will do my best to find some more time.

With regards,
Lucas
